#+TITLE: Apuntes para factibilidad


* Introducción

  Este documento sirve para mantener apuntes a la hora de elaborar el
  informe final del curso de Introducción al trabajo de título
  (CC6908). Todo el contenido de este documento debe ser incorporado
  al reporte final, pero siempre se debe considerar este documento
  como *apuntes*.
  #+TITLE: Apuntes para factibilidad


* Introducción

  Este documento sirve para mantener apuntes a la hora de elaborar el informe final del curso de Introducción al trabajo de título (CC6908). Todo el contenido de este documento debe ser incorporado al reporte final, pero siempre se debe considerar este documento como *apuntes*.

* Objetivos de la Memoria

El objetivo de esta memoria es evaluar el uso de pomodoro y los
impactos que pueda tener implementar gamification en la técnica.

Buscamos dos objetivos en este trabajo

1. Una aplicación de pomodoro con elementos de Gamification
2. Un estudio de la efectividad de pomodoro y gamification sobre flujos de trabajo.

** Aplicación Pomodoro

La aplicación que buscamos hacer necesita lo siguiente:

- Timer de 25 minutos
- Anuncio de pausas cortas (5min) y pausas largas (25-30min)
- Snooze (alargue) de pausas o timer de 25 min de trabajo
- Proveer estadísticas de uso (pomodoros cumplidos, snoozes y tiempos de descanso como *mínimo*)
- Incorporación de elementos de gamification en forma de mensajes personales y dirigidos.

** Mediciones y resultados del trabajo



** Encuestas de Satisfacción

* Aplicaciones Parecidas

Haremos una búsqueda en algunos repositorios conocidos y listaremos
todas las aplicaciones que hay para pomodoro.

En esta sección sólo listamos aquellas que estén relacionadas con
cualquier funcionalidad que queramos cumplir dentro del
proyecto. Idealmente incluiremos URL al proyecto

** Repositorios: Debian oficial, Arch Linux Oficial y AUR.

*** Arch Linux

 Usamos la herramienta para el [[https://aur.archlinux.org/][AUR]], [[https://github.com/Jguer/yay][yay]]. De esta manera obtenemos los
 paquetes en el AUR y los oficiales de Arch Linux

 #+BEGIN_SRC sh
 yay -Ss pomodoro
 #+END_SRC

 Que nos entrega la salida:

 #+BEGIN_EXAMPLE
 aur/pomodairo 1.9-1 (+0 0.00%)
     An Adobe Air application for working with the Pomodoro technique
 aur/ketchup-bin 0.1.0-4 (+0 0.00%)
     a pomodoro timer using client <-> server architecture
 aur/i3-gnome-pomodoro-git r45.7e654f6-1 (+1 0.13%)
     Integrate gnome-pomodoro into i3
 aur/omodoro-git r27.51574fd-2 (+1 0.00%)
     Simple commandline tool to use the pomodoro technique
 aur/spt 0.4-1 (+1 0.00%)
     Simple pomodoro timer that doubles your efficiency
 aur/ketchup-git 0.0.1-1 (+1 0.00%)
     a pomodoro timer using client <-> server architecture
 aur/pomodoro-applet 1.0-1 (+1 0.00%) (Orphaned)
     GNOME Panel applet for timing the intervals used in the Pomodoro Techinique(tm)
 aur/my-agile-pomodoro 4.1.1-1 (+2 0.00%) (Out-of-date 2016-05-09)
     myAgilePomodoro - Time management software that brings you the best of Agile practices and the Pomodoro Technique, written in Java
 aur/pymodoro-git r101.0136d4c-1 (+3 0.47%)
     Pomodoro for Xmobar or Dzen
 aur/tomatoapp-bzr r62-1 (+4 0.27%)
     A simple pomodoro app designed for Elementary OS.
 aur/tomate-gtk 0.8.0-1 (+4 0.00%)
     A timer for the Pomodoro Technique
 aur/python-tomate 0.8.0-1 (+5 0.00%)
     A pomodoro timer
 aur/pomodoneapp 1.5.1320-1 (+9 0.01%)
     Pomodoro timer for your favourite productivity tool
 aur/flow-pomodoro 1.2.0-4 (+10 0.60%)
     A pomodoro app that blocks distractions while you work.
 aur/gnomato 1.1.0-3 (+11 0.01%) (Orphaned)
     A timer for Pomodoro Technique
 aur/potato 6-1 (+11 0.02%)
     A pomodoro timer for the shell
 aur/gnome-shell-pomodoro-git r945.f002440-3 (+14 0.00%)
     A time management utility for GNOME based on the pomodoro technique
 aur/tomighty 0.7.2-1 (+51 0.31%)
     Desktop timer for Pomodoro Technique users
 aur/gnome-shell-pomodoro 0.13.4-1 (+70 3.10%) (Installed)
     A time management utility for GNOME based on the pomodoro technique
 #+END_EXAMPLE

 En una tabla se ve mejor:

 |-------------------+----------------------------------------------------------------------------|
 | Proyecto          | Descripción                                                                |
 |-------------------+----------------------------------------------------------------------------|
 | [[https://code.google.com/archive/p/pomodairo/][Pomodairo]]         | Aplicación en Adobe AIR para Pomodoro                                      |
 | [[https://github.com/jreinert/ketchup][Ketchup]]           | Implementación en Crystal de Pomodoro usando arq. cliente/servidor.        |
 | [[https://github.com/okraits/omodoro][Omodoro]]           | CLI para Pomodoro hecha en Python. Sólo funciona en shells                 |
 | [[https://github.com/pickfire/spt][spt]]               | Un timer simple de pomodoro (no tiene más datos)                           |
 | [[https://sourceforge.net/projects/mypomodoro/][myAgilePomodoro]]   | Completo software de manejo de tiempo escrito en Java                      |
 | [[https://github.com/luizaugustomm/tomato][Tomatoapp]]         | Una aplicación simple para Pomodoro en ElementaryOS                        |
 | [[https://github.com/eliostvs/tomate-gtk][Tomate GTK]]        | Un timer simple para Pomodoro hecho en GTK                                 |
 | [[https://pomodoneapp.com/][PomoDoneApp]]       | Un timer Pomodoro para otras apps (Trello, Todoist, Evernote, entre otros) |
 | [[https://github.com/iamsergio/flow-pomodoro][Flow Pomodoro]]     | Un timer Pomodoro que bloquea distracciones                                |
 | [[https://github.com/diegorubin/gnomato][Gnomato]]           | Otro timer Pomodoro que incorporta listas [[https://zenhabits.net/zen-to-done-ztd-the-ultimate-simple-productivity-system/][ZTD]]                              |
 | [[https://github.com/Bladtman242/potato][Potato]]            | Un timer pomodoro para una /shell/                                         |
 | [[http://tomighty.org/][Tomighty]]          | Un timer de escritorio desarrollado *para* la técnica Pomodoro             |
 | [[http://gnomepomodoro.org/][Pomodoro en GNOME]] | Un timer pomodoro para el Desktop Environment GNOME                        |
 |-------------------+----------------------------------------------------------------------------|



*** Debian oficial

Los [[https://packages.debian.org/search?keywords=pomodoro&searchon=names&suite=stretch&section=all][resultados de la búsqueda]] para Debian stretch con keyword =pomodoro= son los siguientes:

1. =gnome-shell-pomodoro= descrito en Arch Linux
2. =gnome-shell-pomodoro-data= Datos de /independientes de la arquitectura/ usados por el timer pomodoro de GNOME Shell

** Workrave

[[http://www.workrave.org/][Workrave]] es un proyecto [[https://github.com/rcaelers/workrave][Open Source]] dedicado a minimizar [[https://es.wikipedia.org/wiki/Movimientos_repetitivos][Lesiones por
movimiento repetitivo]], funciona forzando al usuario a pausar su flujo
de trabajo cada cierto tiempo.

Si bien no está dedicado a Pomodoro /per-se/, nos es útil en este
trabajo por su característica de descanso. La aplicación contiene
bloqueo de pantalla que nos puede ser increíblemente útil a la hora de
tener que mostrarle pausas a los usuarios. En el peor de los casos,
podemos reusar el código específico de esta funcionalidad aparte e
implementarla en las plataformas deseadas de forma aparte.

** Comercial



* Funcionalidades

** Definiciones
   - Timer 25 minutos :: La aplicación muestra un timer de 25 minutos
        y lo contabiliza como un Pomodoro, esta feature es esencial
        para pomodoro y se asume que nuestra aplicación la tendrá y
        todas las otras aplicaciones también
   - Estadísticas :: Muestra estadísticas de cualquier índole:
                     Pomodoros diarios, Pomodoros por tarea, pomodoros
                     tomados, pomodoros ignorados y/o interrupciones
   - Screen Block :: Se bloquea la pantalla durante cualquier tipo de
                     descanso
   - Snooze :: Se puede alargar el tiempo de trabajo de un pomodoro a
               voluntad del usuario
   - Gamification :: La aplicación aplica gamification de cualquier
                     tipo
   - Pausa larga :: La aplicación anuncia pausas largas y las
                    diferencia de las cortas
   - Lista :: La aplicación contiene una lista de =Tareas por hacer
              hoy=, según lo especificado en la técnica pomodoro

** En aplicaciones analizadas
  A continuación se puede ver una matriz de funcionalidades en las
  apps antes descritas.

  Asumiremos que todas las aplicaciones tienen el timer y no las
  mostraremos si sólo cumplen con dicha función

| Producto        | Estadísticas | Bloqueo | Snooze | gamification | Pausa larga | Lista    |
|-----------------+--------------+---------+--------+--------------+-------------+----------|
| Workrave        |              | X       |        |              |             |          |
| Pomodairo       | X            |         |        |              |             | X        |
| Omodoro         |              |         | X      |              | X           |          |
| myAgilePomodoro | X            |         | X      |              | X           | X        |
| Tomate Gtk      | X (sesiones) |         |        |              |             | X        |
| PomoDoneApp     | X (apps)     |         |        |              |             | X (apps) |
| Gnomato         |              |         |        |              | X           | X        |
| Tomighty        | X (sesiones) |         | X      |              | X           |          |
| Ext. GNOME      | X            | X (GDM) | X      |              | X           |          |

** Deseos en la aplicación
|   Prototipo | Timer por el dia | Screen Block | ... |
|-------------+------------------+--------------+-----|
|           1 |                  |              |     |
|           2 |                  |              |     |
|           3 |                  |              |     |
| Extension A |                  |              |     |
|           B |                  |              |     |
* Recursos
** Biblografia
*** Pomodoro

    [[https://francescocirillo.com/products/the-pomodoro-technique][Artículo
    original]] por Franceso Cirillo.

*** Flow
*** Gamification
** Open Source pomodoro
** Bibliotecas gráficas

   Tenemos variadas:
*** Móviles
**** iOS

     1. [[https://developer.apple.com/swift/][Swift]], nativo para iOS
**** Android

     1. [[https://developer.android.com/training/basics/firstapp/][Android Studio]]? Parece que es la forma de hacer aplicaciones móviles nativas
**** Multiplataforma

     1. [[https://facebook.github.io/react-native/][React Native]], framework multiplataforma basado en =React= y =Javascript=
*** Escritorio

    No caeremos en el juego de tratar de buscar nada multiplataforma
    por la multiplicidad de opciones que existen en cada caso

    1. [[https://www.qt.io/][Qt]], Framework multiplataforma para =C++=
    2. [[https://electronjs.org/][Electron]], Framework multiplataforma para apps =Javascript=

** Codigo para tocar sonido / video

*** Javascript
    1. [[https://www.npmjs.com/package/audio5][Audio5js]]
    2. [[https://howlerjs.com/][howler.js]]


*** C++

    1. [[http://www.portaudio.com/][PortAudio]]
    2. Quedan más.. subcódigos VLC/Lollypop/Banshee/Amarok/etc..

** Protocolos para recibir / intercambiar archivos

*** Manualmente

    Simplemente tocar archivos desde un directorio

*** En la Nube

    1. [[https://www.dropbox.com/][Dropbox]]
    2. WebDAV ([[https://nextcloud.com/][NextCloud, ownCloud, etc...]])
    3. iCloud
    4. Google Drive

*** Compartir desde otras apps.
    1. Telegram
    2. Whatsapp
    3. Email
    4. Notas de voz Android/iOS/macOS/GNOME/KDE

** Encuestas de satisfaccion / eficiencia

* Timeline
    - Junio:
      - [2018-06-26 mar] Lista de aplicaciones similares o relacionadas en repositorios (e.g. Debian, arch, etc..)
      - [2018-06-26 Tue 12:00-12:30] Reunión semanal con Jeremy
    - Julio:
      - [2018-07-03 Tue]
      - [2018-07-05 Thu]-[2018-07-24 Tue] Viaje Jeremy
    - Diciembre
      - [2018-12-28 vie] Actualizar documentación del proyecto en git.
